allowSpawning = true
spawnBadlandsEnderman = true
spawnCaveEnderman = false
spawnCrimsonForestEnderman = true
spawnDarkOakEnderman = true
spawnDesertEnderman = true
spawnEndEnderman = false
spawnEndIslandsEnderman = true
spawnFlowerFieldsEnderman = true
spawnIceSpikesEnderman = true
spawnMushroomFieldsEnderman = true
spawnNetherWastesEnderman = true
spawnOceanEnderman = true
spawnSavannaEnderman = true
spawnSnowyEnderman = true
spawnSoulsandValleyEnderman = true
spawnSwampEnderman = true
spawnWarpedForestEnderman = true
spawnWindsweptHillsEnderman = true

